In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
import numpy as np

:

In [ ]:
df = pd.read_csv('Task 3 and 4_Loan_Data.csv')

df.head()

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
0,8153374,0,5221.545193,3915.471226,78039.38546,5,605,0
1,7442532,5,1958.928726,8228.752520,26648.43525,2,572,1
2,2256073,0,3363.009259,2027.830850,65866.71246,4,602,0
3,4885975,0,4766.648001,2501.730397,74356.88347,5,612,0
4,4700614,1,1345.827718,1768.826187,23448.32631,6,631,0

In [22]:
# quantizing the fico score column in df
num_buckets = 4
df['fico_score'] = pd.qcut(df['fico_score'], q=num_buckets, labels=False)
# get bucket boundaroes
bucket_boundaries = df['fico_score'].unique()
print(bucket_boundaries)
df

[1 0 3 2]

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
0,8153374,0,5221.545193,3915.471226,78039.38546,5,1,0
1,7442532,5,1958.928726,8228.752520,26648.43525,2,0,1
2,2256073,0,3363.009259,2027.830850,65866.71246,4,1,0
3,4885975,0,4766.648001,2501.730397,74356.88347,5,1,0
4,4700614,1,1345.827718,1768.826187,23448.32631,6,1,0
...,...,...,...,...,...,...,...,...
9995,3972488,0,3033.647103,2553.733144,42691.62787,5,3,0
9996,6184073,1,4146.239304,5458.163525,79969.50521,8,1,0
9997,6694516,2,3088.223727,4813.090925,38192.67591,5,0,0
9998,3942961,0,3288.901666,1043.099660,50929.37206,2,2,0
9999,5533570,1,1917.652480,3050.248203,30611.62821,6,3,0

In [ ]:


def kmeans_binning(scores, num_buckets):
    scores = np.array(scores).reshape(-1, 1)
    kmeans = KMeans(n_clusters=num_buckets, random_state=0).fit(scores)
    centers = np.sort(kmeans.cluster_centers_.flatten())
    boundaries = [(centers[i] + centers[i+1]) / 2 for i in range(len(centers)-1)]
    return [-np.inf] + boundaries + [np.inf]

SyntaxError: incomplete input (3329042571.py, line 3)